services:
  - type: web
    name: strava-authorization-service
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: STRAVA_CLIENT_ID
        value: 88569
      - key: STRAVA_CLIENT_SECRET
        value: ac2b07ab6d11cad97c411c963271a2f807ffeedb
      - key: REDIRECT_URI
        value: http://strava-webhooks-p28j.onrender.com/callback
      - key: SESSION_SECRET
        value: "Asperagus!"